import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { inter } from "@/components/ui/font";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import client from "@/libs/interfaces/apolloClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body className={`${inter.variable} font-display `}>{children}</body>
      </ApolloProvider>
    </html>
  );
}
